# Generated by Django 3.2.9 on 2021-12-28 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='view',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
